### ISSUE TITLE
In-app annotation testing

### ISSUE THREAD

**Issue by haywoodsarahe** [CivilWarGovernorsOfKentucky/Mashbill#127]
![image](https://user-images.githubusercontent.com/46460506/87085924-b2922e80-c1fe-11ea-9e8c-9a31a8978978.png)

**Comment by saracarl** [comment]
The last updated-by-Mashbill document I see on Github is this one:
```commit e5a9719a6289fc554e1c33d42b61849094deb671
Author: CWGK-Editor <civilwargovernorsofkentucky.gmail.com>
Date:   Wed Jul 8 12:02:58 2020 -0400

    changes by Mashbill user carlcreasoncwgk
```
which is about the time we were doing the upgrade.  It doesn't look like any document has been checked into Github by Mashbill since the upgrade.  

We'll take a look and figure out why.

**Comment by saracarl** [comment]
Error log shows
```2020-07-09 11:21:17 -0400 /div[1]/div[2]/aside[1]/div[1]/tei[1]/div[1]/text[1]/div[1]/div[2] E. H. Burnside KYR-0001-004-0353 https://hyp.is/sSPUFoGgEeqvmuc4tzlyrw Cound not find fallback element in document 
2020-07-09 11:21:17 -0400 /div[1]/div[2]/aside[1]/div[1]/tei[1]/div[1]/text[1]/div[1]/div[2] E. H. Burnside KYR-0001-004-0353 https://hyp.is/sSPUFoGgEeqvmuc4tzlyrw Could not find element at selector; attempting fallback 
2020-07-09 11:21:17 -0400 /div[1]/div[2]/aside[1]/div[1]/tei[1]/div[1]/text[1]/div[1]/div[1] Garrett Elkin KYR-0001-004-0353 https://hyp.is/rkmBloGgEeqDv1ssP6dLpA Cound not find fallback element in document 
2020-07-09 11:21:17 -0400 /div[1]/div[2]/aside[1]/div[1]/tei[1]/div[1]/text[1]/div[1]/div[1] Garrett Elkin KYR-0001-004-0353 https://hyp.is/rkmBloGgEeqDv1ssP6dLpA Could not find element at selector; attempting fallback 
2020-07-09 11:21:17 -0400 /div[1]/div[2]/aside[1]/div[1]/tei[1]/div[1]/text[1]/div[1]/div[2] W. C Bailey KYR-0001-004-0353 https://hyp.is/ev_yjoGgEeqa6cNmfYRafQ Cound not find fallback element in document 
2020-07-09 11:21:17 -0400 /div[1]/div[2]/aside[1]/div[1]/tei[1]/div[1]/text[1]/div[1]/div[2] W. C Bailey KYR-0001-004-0353 https://hyp.is/ev_yjoGgEeqa6cNmfYRafQ Could not find element at selector; attempting fallback 
2020-07-09 11:21:17 -0400 /div[1]/div[2]/aside[1]/div[1]/tei[1]/div[1]/text[1]/div[1]/div[2] L R McMurtry KYR-0001-004-0353 https://hyp.is/fwI9uoGgEeqFL58xDCwUdw Cound not find fallback element in document 
2020-07-09 11:21:17 -0400 /div[1]/div[2]/aside[1]/div[1]/tei[1]/div[1]/text[1]/div[1]/div[2] L R McMurtry KYR-0001-004-0353 https://hyp.is/fwI9uoGgEeqFL58xDCwUdw Could not find element at selector; attempting fallback 
2020-07-09 11:21:17 -0400 /div[1]/div[2]/aside[1]/div[1]/tei[1]/div[1]/text[1]/div[1]/div[2] Jas A. Anderson KYR-0001-004-0353 https://hyp.is/d6EcToGgEeqNXoPPkTWvdA Cound not find fallback element in document 
2020-07-09 11:21:17 -0400 /div[1]/div[2]/aside[1]/div[1]/tei[1]/div[1]/text[1]/div[1]/div[2] Jas A. Anderson KYR-0001-004-0353 https://hyp.is/d6EcToGgEeqNXoPPkTWvdA
```

This is all since the deployment (and there are more).  Might be why we aren't flushing to github.

**Comment by benwbrum** [comment]
This was a result of some development-level code (to prevent our testing from messing up the documents repository) getting checked in and deployed.  I've updated the code to fix the problem, but someone with access to the server will need to do a `git pull; touch tmp/restart.txt` to deploy it.

**Comment by haywoodsarahe** [comment]
It looks like since the upgrade, Mashbill is producing corrupt TEI for entities (this seems to begin with the first entity I created after the upgrade—N00013041 H. C. Burriss—which doesn't seem to have pushed at all). It seems that only some of the newly created entities since then are pushing to Github, but are showing the same issue (plus older entities that have simply been Updated). And after that, the pages on the site show an Error 404. The document XML seems to be ok. A couple examples: 

P00000478 This entity was created a long time ago but corrupted by the most recent update to it.
N00013055 This is a newly created entity.

I'll continue to comb through the updates from the past couple of day to log the xml documents that will need to be fixed in the repository. 
![image](https://user-images.githubusercontent.com/46460506/87719204-ffd34a80-c780-11ea-871a-32b2f5acedbb.png)

**Comment by haywoodsarahe** [comment]
![image](https://user-images.githubusercontent.com/46460506/87796531-7ae74000-c817-11ea-880c-3dab65584b68.png)

**Comment by haywoodsarahe** [comment]
![image](https://user-images.githubusercontent.com/46460506/87796880-f8ab4b80-c817-11ea-9e63-ebe4bd49d4ea.png)

**Comment by saracarl** [comment]
Fixed the "highlight annotations in blue text" issue.  Checked in but not deployed, yet.

**Comment by benwbrum** [comment]
We've fixed the problem with Mashbill corrupting entities, so after the code is deployed, the following files will need to be updated:

```
P00000542.xml:                <place xml:id="<%= entity.ref_id%>">
P00000554.xml:                <place xml:id="<%= entity.ref_id%>">
P00000555.xml:                <place xml:id="<%= entity.ref_id%>">
P00000564.xml:                <place xml:id="<%= entity.ref_id%>">
P00004352.xml:                <place xml:id="<%= entity.ref_id%>">
P00005286.xml:                <place xml:id="<%= entity.ref_id%>">
P00005395.xml:                <place xml:id="<%= entity.ref_id%>">
P00005549.xml:                <place xml:id="<%= entity.ref_id%>">
P00007210.xml:                <place xml:id="<%= entity.ref_id%>">
P00008733.xml:                <place xml:id="<%= entity.ref_id%>">
P00009448.xml:                <place xml:id="<%= entity.ref_id%>">
P00012630.xml:                <place xml:id="<%= entity.ref_id%>">
```

We think that the problem with the entity highlights was due to a problem unrelated to the old Hypothesis group.  Mashbill was coloring only those entities that had been marked up within Hypothesis in the in-app document display, but was not coloring entities which had been annotated on the discovery site.  We've added coloring to the latter--coloring any `persName`/`placeName`, etc. tags--and would like to know if that fixes both of the second two issues.

**Comment by haywoodsarahe** [comment]
![Error MB](https://user-images.githubusercontent.com/46460506/88219266-57653080-cc2f-11ea-8f39-375bb6401a75.PNG)

I'm running into this error in Mashbill for recently uploaded pages (that seem to be looking fine in the website).

**Comment by benwbrum** [comment]
I've split this out into #128

**Comment by haywoodsarahe** [comment]
In response to a couple comments above, I checked on the same few documents that were having the issue of not highlighting/tagging in Mashbill. After I updated them, there were no changes. I reverted and reapplied annotations in order start clean after that. Still no changes, still missing the same tags. These are:
KYR-0002-225-0063
KYR-0002-009-0011
KYR-0001-004-1381
KYR-0001-004-1390
KYR-0001-004-0088

Though we brought this up in the In-app Annotation issue (as it relates to the blue highlights not showing up in Mashbill), this relates to a preceding issue about missing tags in general. Jeff recently sent an email update with this information but I wanted to keep track of it here as well.

**Comment by haywoodsarahe** [comment]
We've run into the following issue, and I think that comment might belong here. Document KYR-0002-079-0002 isn't pulling up in Mashbill (but is on the discovery site). The document search results bring up a list of documents but not this particular one.

**Comment by benwbrum** [comment]
It looks like this is probably a file encoding issue based on the Windows line-feed characters [visible in Github](https://github.com/CivilWarGovernorsOfKentucky/Documents/blob/master/xml/KYR-0002-079-0002.xml)
